version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Istanbul"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
    groups:
      gradle-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:30"
      timezone: "Europe/Istanbul"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
