plugins { id 'com.android.application' }

android {
    namespace 'com.mehmetcerdik.ownerai'
    compileSdk 35
    buildToolsVersion '35.0.0'

    defaultConfig {
        applicationId 'com.mehmetcerdik.ownerai'
        minSdk 26
        targetSdk 35
        versionCode 4
        versionName '1.2.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
