package com.mehmetcerdik.ownerbridge;
import android.app.Activity;import android.content.ClipData;import android.content.ClipboardManager;import android.content.Intent;import android.content.pm.PackageInfo;import android.os.Build;import android.os.Bundle;import android.provider.Settings;import android.widget.Button;import android.widget.LinearLayout;import android.widget.ScrollView;import android.widget.TextView;import org.json.JSONObject;import java.io.File;import java.io.FileInputStream;import java.security.MessageDigest;
public final class BridgeEvidenceActivity extends Activity{
 private TextView v;
 @Override protected void onCreate(Bundle s){super.onCreate(s);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);int p=(int)(16*getResources().getDisplayMetrics().density);r.setPadding(p,p,p,p);TextView t=new TextView(this);t.setText("MEHMET PRIVILEGED BRIDGE — FINAL EVIDENCE");t.setTextSize(20);r.addView(t);Button a=new Button(this);a.setText("Accessibility Ayarlarını Aç");a.setOnClickListener(x->startActivity(new Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS)));r.addView(a);Button c=new Button(this);c.setText("Kanıtı Kopyala");c.setOnClickListener(x->{((ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("MEHMET Bridge final evidence",evidence().toString()));refresh();});r.addView(c);v=new TextView(this);v.setTextIsSelectable(true);r.addView(v);ScrollView sc=new ScrollView(this);sc.addView(r);setContentView(sc);refresh();}
 @Override protected void onResume(){super.onResume();refresh();}private void refresh(){if(v!=null)v.setText(evidence().toString(2));}
 private JSONObject evidence(){JSONObject o=new JSONObject();try{PackageInfo pi=getPackageManager().getPackageInfo(getPackageName(),0);String h=sha(new File(getApplicationInfo().sourceDir)),sig=BridgeSecurity.getSigner(this,getPackageName()),owner=BridgeSecurity.getSigner(this,BridgeSecurity.CORE_PACKAGE);boolean svc=BridgeAccessibilityService.instance()!=null,launch=BridgeEvidenceStore.hasPass(this,"LAUNCH_APP"),swipe=BridgeEvidenceStore.hasPass(this,"SWIPE"),type=BridgeEvidenceStore.hasPass(this,"TYPE_TEXT");
  o.put("version",1).put("status","BRIDGE_FINAL_EVIDENCE_CAPTURED").put("bridge_package",getPackageName()).put("bridge_version_name",pi.versionName==null?"":pi.versionName).put("bridge_version_code",Build.VERSION.SDK_INT>=28?pi.getLongVersionCode():pi.versionCode).put("bridge_artifact_sha256",h).put("bridge_signer_cert_sha256",sig==null?"":sig).put("owner_package",BridgeSecurity.CORE_PACKAGE).put("owner_signer_cert_sha256",owner==null?"":owner).put("network_permission","NONE").put("service_connected",svc).put("launch_app_pass",launch).put("swipe_pass",swipe).put("type_text_pass",type).put("verify_postcondition_pass",launch&&swipe&&type).put("events",BridgeEvidenceStore.read(this)).put("captured_at_epoch_ms",System.currentTimeMillis());
 }catch(Throwable e){try{o.put("status","BRIDGE_FINAL_EVIDENCE_BUILD_FAILED");}catch(Throwable ignored){}}return o;}
 private String sha(File f)throws Exception{MessageDigest d=MessageDigest.getInstance("SHA-256");byte[]b=new byte[65536];try(FileInputStream i=new FileInputStream(f)){for(int n;(n=i.read(b))>0;)d.update(b,0,n);}StringBuilder s=new StringBuilder();for(byte x:d.digest())s.append(String.format("%02x",x&255));return s.toString();}
}